etn-ccis/blui-react-native-cli-templates

- .circleci/config.yml
I forgot to put this in the authentication templates PR! 🙄 
- Update circle ci config to include npm publishing authentication templates
> Update circleci config to include npm publishing for authentication templates

- authentication-typescript/package.json
- authentication/package.json
- blank-typescript/package.json
- blank/package.json
- routing-typescript/package.json
- routing/package.json
- Update template README's for the official 1.0.0 release
> Update template README's for official 1.0.0 release

- demo/android/build.gradle
- demo/yarn.lock
- Update minSdkversion and yarn.lock for demo
> Update minSdkversion and yarn.lock for demo

- authentication-typescript/CHANGELOG.md
- authentication/CHANGELOG.md
- blank-typescript/CHANGELOG.md
- blank/CHANGELOG.md
- routing-typescript/CHANGELOG.md
- routing/CHANGELOG.md
Fixes PXBLUE-1958
- Add package release dates to changelog
> Add package release date to changelog

- .circleci/config.yml
- PUBLISHING.md
- authentication-typescript/package.json
- authentication/package.json
- blank-typescript/package.json
- blank/package.json
- routing-typescript/package.json
- routing/package.json
> Update publishing script

- authentication-typescript/CHANGELOG.md
- authentication-typescript/dependencies.json
- authentication-typescript/package.json
- authentication/CHANGELOG.md
- authentication/dependencies.json
- authentication/package.json
- Drop dependency of react-native-webview to match requirements of react-native-auth-workflow
> Drop peer dependencies to compatible version

- authentication-typescript/CHANGELOG.md
- authentication/CHANGELOG.md
- Update the changelog release date
> Update changelog for release

- .circleci/config.yml
> Use auto tag

- authentication-typescript/template/App.tsx
- authentication/template/App.js
- blank-typescript/template/App.tsx
- blank/template/App.js
- routing-typescript/template/App.tsx
- routing/template/App.js
> Add license

- authentication-typescript/package.json
- authentication/package.json
- blank-typescript/package.json
- blank/package.json
- routing-typescript/package.json
- routing/package.json
Add tag commands so circleCI can auto-tag
> Add tag command to package.json

- authentication-typescript/template/App.tsx
- authentication/template/App.js
- blank-typescript/template/App.tsx
- blank/template/App.js
- routing-typescript/template/App.tsx
- routing/template/App.js
Fixes #99 https://github.com/pxblue/pxblue-cli/issues/99
- update both blank templates to use SafeAreaProvider
- 
- 
-
> update blank temp to use SafeAreaProvider

- authentication-typescript/template/src/navigation/index.tsx
- authentication/template/src/navigation/index.js
- demo/App.js
- routing-typescript/template/src/navigation/index.tsx
- routing/template/src/navigation/index.js
- Sets a max width for drawer in case the device width is smaller than 300.
> Add max width to drawer

- authentication-typescript/CHANGELOG.md
- authentication-typescript/dependencies.json
- authentication-typescript/package.json
- authentication/CHANGELOG.md
- authentication/dependencies.json
- authentication/package.json
- blank-typescript/CHANGELOG.md
- blank-typescript/dependencies.json
- blank-typescript/package.json
- blank/CHANGELOG.md
- blank/dependencies.json
- blank/package.json
- package.json
- routing-typescript/CHANGELOG.md
- routing-typescript/dependencies.json
- routing-typescript/package.json
- routing/CHANGELOG.md
- routing/dependencies.json
- routing/package.json
- yarn.lock
- update pxblue react-native package versions
- update change logs
- update root package to reflect versions of eslint & prettier
-
> update template packages

- authentication-typescript/CHANGELOG.md
- authentication-typescript/dependencies.json
- authentication-typescript/package.json
- authentication/CHANGELOG.md
- authentication/dependencies.json
- authentication/package.json
- Fix auth workflow version number
> Fix auth workflow version number

- authentication-typescript/CHANGELOG.md
- authentication-typescript/dependencies.json
- authentication-typescript/package.json
- authentication/CHANGELOG.md
- authentication/dependencies.json
- authentication/package.json
- blank-typescript/CHANGELOG.md
- blank-typescript/dependencies.json
- blank-typescript/package.json
- blank/CHANGELOG.md
- blank/dependencies.json
- blank/package.json
- routing-typescript/CHANGELOG.md
- routing-typescript/dependencies.json
- routing-typescript/package.json
- routing/CHANGELOG.md
- routing/dependencies.json
- routing/package.json
Add react-native-vector-icon dependency to all templates
> Add react-native-vector-icon dependency to all templates

- authentication-typescript/CHANGELOG.md
- authentication-typescript/dependencies.json
- authentication-typescript/package.json
- authentication/CHANGELOG.md
- authentication/dependencies.json
- authentication/package.json
- blank-typescript/CHANGELOG.md
- blank-typescript/dependencies.json
- blank-typescript/package.json
- blank/CHANGELOG.md
- blank/dependencies.json
- blank/package.json
- routing-typescript/CHANGELOG.md
- routing-typescript/dependencies.json
- routing-typescript/package.json
- routing/CHANGELOG.md
- routing/dependencies.json
- routing/package.json
Publish various versions of templates
> Publish various versions of templates

- authentication-typescript/CHANGELOG.md
- authentication/CHANGELOG.md
- blank-typescript/CHANGELOG.md
- blank/CHANGELOG.md
- routing-typescript/CHANGELOG.md
- routing/CHANGELOG.md
update changelog release dates
> Update Changelog release dates

- authentication-typescript/CHANGELOG.md
- authentication-typescript/dependencies.json
- authentication-typescript/package.json
- authentication/dependencies.json
- authentication/package.json
- blank-typescript/CHANGELOG.md
- blank-typescript/package.json
- blank/CHANGELOG.md
- blank/package.json
- routing-typescript/CHANGELOG.md
- routing-typescript/package.json
- routing/CHANGELOG.md
- routing/package.json
- Prepare to publish all templates v2.1.0
> Prepare to publish all templates v2.1.0

- demo/App.tsx
- demo/src/navigation/index.tsx
- demo/src/navigation/navigation-drawer.tsx
- routing-typescript/CHANGELOG.md
- routing-typescript/dependencies.json
- routing-typescript/template/App.tsx
- routing-typescript/template/src/navigation/index.tsx
- routing-typescript/template/src/navigation/navigation-drawer.tsx
Fixes 4881 .
- Update dependencies to run routing typescript
- 
-
-
-
-
> Update dependencies for routing typescript

- routing-typescript/package.json
Fixes 4955 .
- Publish alpha package
-
-
-
- 
- Once an alpha package is published will test it in CLI and raise PR for an official version
> Publish alpha package for routing template

- .circleci/config.yml
- .eslintrc.js
- package.json
- yarn.lock
Fixes BLUI-5381.
- update some dependencies & circleCI
- noticed we had an dependabot update that failed
- https://app.circleci.com/pipelines/github/etn-ccis/blui-react-native-cli-templates
-
-
- is this eslint config proper for this repo?
> Fix lint errors dependabots

- .github/workflows/blui-ci.yml
Fixes BLUI-5594.
- update the working directory
-
-
-
-
-
> Update working directory

- .github/workflows/blui-ci.yml
Fixes #  Failing actions
- Added checkout step before changing the directory
-
-
-
> Added checkout step before changing the directory

- authentication-typescript/package.json
- blank-typescript/package.json
- routing-typescript/package.json
> package release R32

- authentication-typescript/CHANGELOG.md
- blank-typescript/CHANGELOG.md
- routing-typescript/CHANGELOG.md
Fixes # . changed date for changelog
-
-
-
-
-
-
> update date on changelog
